# Generated by Django 3.2 on 2023-05-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscridet',
        ),
    ]
