# Generated by Django 3.2 on 2023-05-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('tegs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teg',
            new_name='Tag',
        ),
    ]
